# Generated by Django 4.1 on 2022-08-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knitted_back', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='uploads/icons8-yarn-100.png', upload_to='uploads/'),
        ),
    ]
