# Generated by Django 4.1 on 2022-08-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knitted_back', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='uploads/640px-Several_packages_of_yarn.jpg', upload_to='uploads/'),
        ),
    ]
