# Generated by Django 4.1 on 2022-09-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knitted_back', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
